all: RL_glue RL_experiment RL_agent RL_environment
include RL_glue.makefile
include RL_experiment.makefile
include RL_agent.makefile
include RL_environment.makefile
include RL_network.makefile

clean:
	rm -f bin/*
	rm -f Build/*

