all: RL_glue RL_agent RL_environment RL_experiment
include RL_glue.makefile
include RL_agent.makefile
include RL_environment.makefile
include RL_experiment.makefile

clean:
	rm -fr Build/*
	rm -fr bin/*
